version: '2.1'

services:

  pocket-node:
    build: .
    image: sofwerx/pocket-node
    container_name: pocket-node
    hostname: pocket-node
    restart: on-failure
    environment:
      POCKET_NODE_SERVER_PORT: ${POCKET_NODE_SERVER_PORT}
      POCKET_NODE_PLUGIN_ETH: ${POCKET_NODE_PLUGIN_ETH}
      POCKET_NODE_PLUGIN_ETH_NODE: ${POCKET_NODE_PLUGIN_ETH_NODE}
      POCKET_NODE_PLUGIN_ETH_NETWORK_ID: ${POCKET_NODE_PLUGIN_ETH_NETWORK_ID}
 
